### ISSUE TITLE
Error when calling CsharpGeneration.App with no references

### ISSUE THREAD

**Issue by anpaz-msft** [microsoft/qsharp-runtime#27] opened 2019-07-22 22:17 UTC
## Describe the bug
Calling the CsharpGeneration.App with no references causes an exception, and the code can't be compiled even if it needs no references.

## To Reproduce
1. Clone the repo
2. From the command line change to `src\Simulation\CsharpGeneration.App`
3. Run `dotnet run -- -i ..\Intrinsic\Math\Math.qs -o ..`

## Expected behavior
The codegen for `Math.qs` should be generated in the `..` folder.

## Actual behavior
```

Unhandled Exception: System.ArgumentException: Object of type 'System.Object[]' cannot be converted to type 'System.Collections.Generic.IEnumerable`1[System.String]'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at CommandLine.Core.InstanceBuilder.BuildImmutable[T](Type typeInfo, Maybe`1 factory, IEnumerable`1 specProps, IEnumerable`1 specPropsWithValue, List`1 setPropertyErrors)
   at CommandLine.Core.InstanceBuilder.<>c__DisplayClass0_0`1.<Build>b__5()
   at CommandLine.Parser.ParseArguments[T](IEnumerable`1 args)
   at Microsoft.Quantum.QsCompiler.CsharpGeneration.Program.main(String[] args) in C:\Repos\Solid\submodules\qsharp-runtime\src\Simulation\CsharpGeneration.App\Program.fs:line 64
```

## System information
- OS: Windows
- .NET Core Version: `2.2.103`
- IQ# Version: n/a
- Python Version: n/a

**Comment by niontive** [comment] 2019-10-29 00:22
Taking a look now

**Comment by niontive** [comment] 2019-10-29 00:56
Unable to reproduce.

**System information**

- OS: Windows
- .NET Core SDKs Installed: 2.1.701, 2.1.801, 2.2.402, 3.0.100
- IQ# Version: n/a
- Python Version: n/a

**Comment by adrianwyatt** [comment] 2019-10-29 00:58
Confirm no repro.

**Comment by bettinaheim** [comment] 2019-11-12 18:39
Thanks @niontive & @adrianwyatt for checking! Since this seems to have been resolved and the code gen app will be obsolete in the near future (to be replace by the command line interface of the[ Q# compiler](https://github.com/microsoft/qsharp-compiler)) I am closing this.

**Closed by bettinaheim** 2019-11-12 18:39 UTC
Labels: bug, good first issue
